config/routes.rb
Rails.application.routes.draw do
  get 'search' => 'searchs#search'
devise_for :users
  root to: 'homes#top'
  get '/home/about' => 'homes#about', as: 'about'

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings'
    get 'followers' => 'relationships#followers'
  end

  resources :books do
    resources :book_comments, only: [:create,:destroy]
    resource :favorites, only: [:create,:destroy]
  end

  resources :ranks, only: [:index]

  # resources :searchs, only: [:index]
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_comment_params)
    # comment = PostComment.new(post_comment_params)
    # comment.user_id = current_user.id
    # この記述と変わりなし
    @book_comment.book_id = @book.id
    @book_comment.save
    # redirect_to book_path(@book)
    # 非同期通信の際、消す
  end

  def destroy
    @book = Book.find(params[:book_id])
    @book_comment = @book.book_comments.find(params[:id])
     if @book_comment.user != current_user
         redirect_to user_path(@user)
     end
    @book_comment.destroy
    # redirect_to book_path(@book)
    # 非同期通信
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_book_comment.html.erb
<div class="comments">
<% book.book_comments.each do |book_comment| %>
<!--アクション内の定義と名前は揃える-->
    <%= attachment_image_tag user, :profile_image, size: "60x60", format: 'jpeg', fallback: "no_image.jpg" %>
    <%= book_comment.comment %>
    <% if book_comment.user == current_user %>
    <span class="comment-delete">
      <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class:"btn btn-danger" %>
      <!--remote: trueでjs.erbファイルに飛ばす-->
    </span>
    <% end %>
    <p><%= book_comment.user.name %></p>
<% end %>
</div>
<div class="new-comments">
  <%= form_with(model:[book, book_comment], remote: true) do |comment| %>
  <!--モデルの指定も@は なし-->
  <!--remote: trueでjs.erbファイルに飛ばす-->
    <%= comment.text_area :comment, rows:'5', class:"col-md-10" %>
    <%= comment.submit "送信" %>
  <% end %>
</div>

app/views/book_comments/_of_comments.html.erb
<h2>Book detail</h2>

<table class="table">
	<thead>
		<tr>
			<th>name</th>
			<th>title</th>
			<th>body</th>
			<% if book.user == current_user %>
				<th>編集</th>
				<th>削除</th>
			<% end %>
			<th>favo</th>
			<th>comment</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>
				<%= link_to user_path(book.user) do %>
					<!--%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no-image.jpg" %><br>-->
					<%= attachment_image_tag user, :profile_image, size: "50x50", format: 'jpeg', fallback: "no_image.jpg", remote: true %><br>
					<%= book.user.name %>
				<% end %>
			</td>
			<td><%= link_to book.title, book_path(book) %></td>
			<td><%= book.body %></td>
			<% if book.user == current_user %>
			<td><%= link_to "Edit", edit_book_path(book), class: "btn-sm btn-success edit_book_#{book.id}" %></td>
			<td><%= link_to "Destroy", book_path(book), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
			<% end %>
			<td class=<%= "favorites" +book.id.to_s %>>
					<!--to_i=integer(整数)-->
					<!--to_s=string(文字列)-->
				<%= render 'favorites/favorite', book: book %>
					<!--引数の代入はeach分のブロック数を代入-->
			</td>
			<td>コメント件数:<%= book.book_comments.count %></td>
		</tr>
	</tbody>
</table>

<table class="table">
	<thead>
		<tr>
			<th>Photo</th>
			<th>name</th>
			<th>comment</th>
			<th>destroy</th>
		</tr>
	</thead>
	<tbody>
		<% book.book_comments.each do |book_comment| %>
		<tr>
			<td><%= attachment_image_tag user, :profile_image, size: "50x50", format: 'jpeg', fallback: "no_image.jpg" %></td>
			<td><%= book_comment.user.name %></td>
			<td><%= book_comment.comment %></td>
			<td>
				<% if book_comment.user == current_user %>
          <span class="">
            <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class:"btn btn-danger" %>
            <!--remote: trueでjs.erbファイルに飛ばす-->
          </span>
      	<% end %>
			</td>
		</tr>
		<!--アクション内の定義と名前は揃える-->
		<% end %>
	</tbody>
</table>

<div class="new-comments">
	<h3>コメント入力</h3>
  <%= form_with(model:[book, book_comment], remote: true) do |comment| %>
  <!--部分テンプレートの場合 モデルの指定も@は なし-->
  <!--remote: trueでjs.erbファイルに飛ばす-->
    <%= comment.text_area :comment, rows:'5', class:"col-md-10" %>
    <%= comment.submit "送信" %>
  <% end %>
</div>

app/views/book_comments/create.js.erb
$('.of_comments'+<%= @book.id %>).html("<%= j(render 'book_comments/of_comments', user: current_user, book: @book, newbook: @newbook, book_comment: @book_comment ) %>");

$('textarea').val('');
<!--投稿後入力欄にコメント内容が残らないようにしている

app/views/book_comments/destroy.js.erb
$('.of_comments'+<%= @book.id %>).html("<%= j(render 'book_comments/of_comments', user: current_user, book: @book, newbook: @newbook, book_comment: @book_comment ) %>");

$('textarea').val('');