config/routes.rb
Rails.application.routes.draw do
  get 'search' => 'searchs#search'
devise_for :users
  root to: 'homes#top'
  get '/home/about' => 'homes#about', as: 'about'

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings'
    get 'followers' => 'relationships#followers'
  end

  resources :books do
    resources :book_comments, only: [:create,:destroy]
    resource :favorites, only: [:create,:destroy]
  end

  resources :ranks, only: [:index]

  # resources :searchs, only: [:index]
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  # followerもfollowedも存在しないmodel
  # フォローする人もされる人もuserモデルなので
  # class_nameをつけることで関連先のモデルを参照する際の名前を変更できる
  # Userを「followerとfollowedに分ける」ことをclass_nameが担当
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  # 相手側の指定？
  def followers
    user = User.find(params[:user_id])
    @user = user.followings
    # ユーザがフォローしているユーザ一覧
  end

  def followings
    user = User.find(params[:user_id])
    @user = user.followers
    # ユーザがフォローされているユーザ一覧
  end

end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/followers.html.erb
<div class="col-md-12">
  <% if @user.exists? %>
  <table class="table">
    <thead>
      <tr>
        <th>Photo</th>
        <th>Name</th>
        <th>フォロー数</th>
        <th>フォロワー数</th>
        <th>フォロー</th>
        <th colspan="6"></th>
      </tr>
    </thead>
    <tbody>
      <% @user.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, size: "50x50", format: 'jpeg', fallback: "no_image.jpg" %></td>
        <td><%= user.name %></td>
        <td><%= user.followers.count %></td>
        <td><%= user.followings.count %></td>
        <td>
          <% if current_user.following?(user) %>
            <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class:"btn btn-primary" %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class:"btn btn-info" %>
          <% end %>
        </td>
        <td><%= link_to "Show", user_path(user) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div><%= link_to "Homeに戻る", user_path(current_user) %></div>
  <% else %>
    <p>ユーザは存在しません</p>
    <div><%= link_to "Homeに戻る", user_path(current_user) %></div>
  <% end %>
</div>

app/views/relationships/followings.html.erb
<div class="col-md-12">
<% if @user.exists? %>
  <table class="table">
    <thead>
      <tr>
        <th>写真</th>
        <th>名前</th>
        <th>フォロー数</th>
        <th>フォロワー数</th>
        <th>フォロー</th>
        <th>詳細</th>
      </tr>
    </thead>
    <tbody>
      <% @user.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, size: "50x50", format: 'jpeg', fallack: "no_image.jpg" %></td>
        <td><%= user.name %></td>
        <td><%= user.followers.count %></td>
        <td><%= user.followings.count %></td>
        <td>
          <% if current_user.following?(user) %>
            <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class:"btn btn-outline-primary" %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class:"btn btn-outline-info" %>
          <% end %>
        </td>
        <td><%= link_to "Show", user_path(user) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div><%= link_to "Homeに戻る", user_path(current_user) %></div>
<% else %>
    <p>ユーザは存在しません</p>
    <div><%= link_to "Homeに戻る", user_path(current_user) %></div>
<% end %>
</div>