config/routes.rb
Rails.application.routes.draw do
  get 'search' => 'searchs#search'
devise_for :users
  root to: 'homes#top'
  get '/home/about' => 'homes#about', as: 'about'

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings'
    get 'followers' => 'relationships#followers'
  end

  resources :books do
    resources :book_comments, only: [:create,:destroy]
    resource :favorites, only: [:create,:destroy]
  end

  resources :ranks, only: [:index]

  # resources :searchs, only: [:index]
end

app/models/user.rb
class User < ApplicationRecord
 # Include default devise modules. Others available are:
 # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
 devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

 has_many :books, dependent: :destroy
 has_many :book_comments, dependent: :destroy
 has_many :favorites, dependent: :destroy
 attachment :profile_image

 # フォロー機能
 #1 仮の名前
 #2 class_nameが中間テーブル指定
 #3 foreign_keyで主キー選択

 # フォローしている人のデータ取得
 has_many :of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
 # フォローしている人のデータをrelationship(中間テーブル)を通して相手側(フォローしている人)と紐付け
 #  has_many :followers, through: :of_relationships, source: :follower と紐付け

 # フォローされている人のデータ取得
 has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
 # フォローしている人のデータをrelationship(中間テーブル)を通して相手側(フォロワー)と紐付け
 #  has_many :followings, through: :relationships, source: :followed と紐付け

 #1 フォロー/フォロワーの記述
 #2 紐付けするデータの指定
 #3 スルーはあるリレーションを他のテーブルを通して実現する際に用いる

 # 自分がフォローしている人
 has_many :followers, through: :of_relationships, source: :follower
 # has_many :of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy と紐付け
 # 自分をフォローしている人(相手側)
 has_many :followings, through: :relationships, source: :followed
 # has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy と紐付け

 validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
 validates :introduction, length: {maximum: 50}

 # フォロー機能
  # フォローをする
  def follow(user_id)
      relationships.create(followed_id: user_id)
      # createメソッドはnewとsaveを合わせた挙動
      # 下記と同様の意味
      # relationship = relationships.new(followed_id: user_id)
      # relationship.save
  end

  # フォロー機能を複数持たないように指定し、削除をする
  def unfollow(user_id)
      relationships.find_by(followed_id: user_id).destroy
      # いいねと同じように、ユーザAがユーザBに対して複数個のフォローを作成することはなく、
      # ユーザBをフォローしている場合、relationshipsテーブルには対応するレコードはただ一つです。
      # そのためfind_byによって1レコードを特定し、destroyメソッドで削除しています。
  end

  # フォローしているユーザを確認する
  def following?(user)
      followings.include?(user)
      # 引数に渡したユーザを、フォローしているかどうかを判定します。
      # include?は対象の配列に引数のものが含まれていればtrue、含まれていなければfalseを返します。
      # @user.followingsは「@userがフォローしているユーザ一覧」ですので、
      # ここに含まれていれば、引数に渡したユーザをフォローしている（true）ことになります。
      # このメソッドは、ビューでフォローする/フォローを外すボタンの表示で用いています。
  end

  # 検索機能
  def self.search(search,word)
   # 前方一致
   if search == "forward_match"
    @user = User.where("name LIKE?","#{word}%")
    # 完全一致
   elsif search == "perfect_match"
    @user = User.where(name:"#{word}")

   else
    @user = User.all
   end
  end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :ensure_correct_user, only: [:update]
  # ↓
  # before_action :ensure_correct_user, only: [:edit, :update]
#   この場合、ensure_correct_userメソッドのbefore_actionにeditを追加してあげる必要があります。
# before_actionによってeditのアクションを起こす前にensure_correct_userメソッドが働きます。
# ensure_correct_userについて詳しく解説すると
# unlessはifの反対で「もし〜でなければ」という意味になりますので
# unless @user == current_user
# もし@userとcurrent_user(ログインしているユーザー)が一致してなければ、という意味になります。
# 一致していなかった場合、ログインしているuserのshowページにリダイレクトする仕組みになっています
  before_action :authenticate_user!
  # ページ遷移設定
  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def create
    @user = User.new(user_params)
    @book.save
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_error_message.html.erb
<% if user.errors.any? %>
  <div class="error_pranation">
      <% user.errors.full_messages.each do |message| %>
    <h2 class="error-text">1 error prohibited this obj from being saved:</h2>
    <ul>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_list.html.erb
<table class="table">
  <h2>User info</h2>
	<tbody>
  	<!--%= attachment_image_tag user, :profile_image, size: "50x50", format: 'jpeg', fallback: "no_image.jpg" %>-->
  	<%= attachment_image_tag user, :profile_image, size: "50x50", format: 'jpeg', fallback: "no_image.jpg" %>
  	<tr>
  		<th>name</th>
  		<th><%= user.name %></th>
  	</tr>
  	<tr>
  		<th>introduction</th>
  		<th><%= user.introduction %></th>
  	</tr>
  	<tr>
  	  <th>follow</th>
  	  <th>
  	    <%= link_to user_followers_path(user) do %>
  	      <%= user.followings.count %>
  	    <% end %>
  	  </th>
  	</tr>
  	<tr>
  	  <th>followers</th>
  	  <th>
  	    <%= link_to user_followings_path(user) do %>
  	      <%= user.followers.count %>
  	    <% end %>
  	  </th>
  	</tr>
  	<tr>
  	  <th>Ranking</th>
  	  <td><%= link_to "Ranking", ranks_path %></td>
  	</tr>
	</tbody>
</table>

<% if user == current_user %>
	<!--%= link_to '設定', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>-->
  <%= link_to "", edit_user_path(user), class:"btn btn-outline-secondary btn-block fas fa-user-cog" %>
<% end %>

<%= render "books/error_message", book: @book %>
<%= form_with model:book, local:true do |f| %>
  <div class=""><%= f.label :title %></div>
  <div><%= f.text_field :title, class: 'book_title' %></div>

  <div class=""><%= f.label :opinion %></div>
  <div><%= f.text_area :body, class: 'book_opinion' %></div>

  <div class="">
    <%= f.submit class: 'btn btn-outline-info mt-3' %>
  </div>
<% end %>

app/views/users/create.js.erb
$('.lists'+<%= @book.id %>).html("<%= j(render 'users/list', user: @user, book: @book )%>");

$('textarea').val('');

app/views/users/destroy.js.erb
$('.lists'+<%= @book.id %>).html("<%= j(render 'users/list', user: @user, book: @book )%>");

$('textarea').val('');

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_with model:@user, local: true do |f| %>

	<!-- エラーメッセージ表示-->
	<%= render "users/error_message", user: @user %>
	<!-- エラーメッセージ表示-->

	<div class="field">
		<%= f.label :title %>
		<%= f.text_field :name, class: "name" %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :profile_image, class: "user_image" %>
	</div>

	<div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/index.html.erb
	<div class="col-md-3 mt-5">
		<div class=<%= "lists" +@book.id.to_s %>>
			<%= render 'users/list', user: current_user, book: @book %>
		</div>
	</div>

	<div class="col-md-8 offset-md-1 mt-5">
	<h2>Users</h2>
	<!--users一覧 -->
	<table class="table">
		<thead>
			<tr>
				<th>image</th>
				<th>name</th>
				<th colspan="3"></th>
				<th colspan="4"></th>

			</tr>
		</thead>

		<tbody>
			<% @users.each do |user| %>
			<tr>
				<!--<td>%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>-->
				<td><%= attachment_image_tag user, :profile_image, size: "50x50", format: 'jpeg', fallback: "no_image.jpg" %></td>
				<td><%= user.name %></td>
				<td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
				<td>
				<% if user != current_user %>
					<% if current_user.following?(user) %>
					<!--自分がフォローしている人がif-->
						<%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-outline-primary" %>
					<% else %>
						<%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-outline-success" %>
					<% end %>
				<% end %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
	<!--users一覧 -->

	</div>

app/views/users/show.html.erb
<div class="col-md-3 mt-5">
	<div class=<%= "lists" +@book.id.to_s %>>
		<%= render 'users/list', user: @user, book: @book %>
	</div>
</div>

<div class="col-md-8 offset-md-1 mt-5">
	<h2>Books</h2>
	<!--books一覧 -->
	<table class="table table-hover table-inverse">
		<thead>
			<tr>
				<th colspan="1"></th>
				<th>Title</th>
				<th>Opinion</th>
				<th>いいね数</th>
			</tr>
		</thead>

		<tbody>
			<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to user_path(book.user) do %>
							<!--%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg" %>-->
							<%= attachment_image_tag book.user, :profile_image, size: "40x40", format: 'jpeg',  fallback: "no_image.jpg" %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<td><%= book.favorites.count %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>