config/routes.rb
Rails.application.routes.draw do
  get 'search' => 'searchs#search'
devise_for :users
  root to: 'homes#top'
  get '/home/about' => 'homes#about', as: 'about'

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings'
    get 'followers' => 'relationships#followers'
  end

  resources :books do
    resources :book_comments, only: [:create,:destroy]
    resource :favorites, only: [:create,:destroy]
  end

  resources :ranks, only: [:index]

  # resources :searchs, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	attachment :profile_image

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
		# いいねした1ユーザのidが存在するかの確認記述
	end

	  # 検索機能
  def self.search(search,word)
   # 前方一致
   if search == "forward_match"
    @book = Book.where("title LIKE?","#{word}%")
    # 完全一致
   elsif search == "perfect_match"
    @book = Book.where(title:"#{word}")

   else
    @book = Book.all
   end
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/rank.rb
class Rank < ApplicationRecord
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  # followerもfollowedも存在しないmodel
  # フォローする人もされる人もuserモデルなので
  # class_nameをつけることで関連先のモデルを参照する際の名前を変更できる
  # Userを「followerとfollowedに分ける」ことをclass_nameが担当
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
 # Include default devise modules. Others available are:
 # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
 devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

 has_many :books, dependent: :destroy
 has_many :book_comments, dependent: :destroy
 has_many :favorites, dependent: :destroy
 attachment :profile_image

 # フォロー機能
 #1 仮の名前
 #2 class_nameが中間テーブル指定
 #3 foreign_keyで主キー選択

 # フォローしている人のデータ取得
 has_many :of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
 # フォローしている人のデータをrelationship(中間テーブル)を通して相手側(フォローしている人)と紐付け
 #  has_many :followers, through: :of_relationships, source: :follower と紐付け

 # フォローされている人のデータ取得
 has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
 # フォローしている人のデータをrelationship(中間テーブル)を通して相手側(フォロワー)と紐付け
 #  has_many :followings, through: :relationships, source: :followed と紐付け

 #1 フォロー/フォロワーの記述
 #2 紐付けするデータの指定
 #3 スルーはあるリレーションを他のテーブルを通して実現する際に用いる

 # 自分がフォローしている人
 has_many :followers, through: :of_relationships, source: :follower
 # has_many :of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy と紐付け
 # 自分をフォローしている人(相手側)
 has_many :followings, through: :relationships, source: :followed
 # has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy と紐付け

 validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
 validates :introduction, length: {maximum: 50}

 # フォロー機能
  # フォローをする
  def follow(user_id)
      relationships.create(followed_id: user_id)
      # createメソッドはnewとsaveを合わせた挙動
      # 下記と同様の意味
      # relationship = relationships.new(followed_id: user_id)
      # relationship.save
  end

  # フォロー機能を複数持たないように指定し、削除をする
  def unfollow(user_id)
      relationships.find_by(followed_id: user_id).destroy
      # いいねと同じように、ユーザAがユーザBに対して複数個のフォローを作成することはなく、
      # ユーザBをフォローしている場合、relationshipsテーブルには対応するレコードはただ一つです。
      # そのためfind_byによって1レコードを特定し、destroyメソッドで削除しています。
  end

  # フォローしているユーザを確認する
  def following?(user)
      followings.include?(user)
      # 引数に渡したユーザを、フォローしているかどうかを判定します。
      # include?は対象の配列に引数のものが含まれていればtrue、含まれていなければfalseを返します。
      # @user.followingsは「@userがフォローしているユーザ一覧」ですので、
      # ここに含まれていれば、引数に渡したユーザをフォローしている（true）ことになります。
      # このメソッドは、ビューでフォローする/フォローを外すボタンの表示で用いています。
  end

  # 検索機能
  def self.search(search,word)
   # 前方一致
   if search == "forward_match"
    @user = User.where("name LIKE?","#{word}%")
    # 完全一致
   elsif search == "perfect_match"
    @user = User.where(name:"#{word}")

   else
    @user = User.all
   end
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def new
    @book = Book.new
  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
    # @book_comment.user_id = @user.id
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      @user = current_user
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
    if @user != current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.delete
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

#   ログイン中にURLを入力すると他人が投稿した本の編集ページに遷移できないようにする
#   def ensure_correct_user
#       @book = Book.find(params[:id])
#       unless @book.user == current_user
#         redirect_to books_path
#       end
#   end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
  def index
    @rankbook = Book.joins(:favorites).group(:book_id).order('count(book_id) desc').limit(5)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :ensure_correct_user, only: [:update]
  # ↓
  # before_action :ensure_correct_user, only: [:edit, :update]
#   この場合、ensure_correct_userメソッドのbefore_actionにeditを追加してあげる必要があります。
# before_actionによってeditのアクションを起こす前にensure_correct_userメソッドが働きます。
# ensure_correct_userについて詳しく解説すると
# unlessはifの反対で「もし〜でなければ」という意味になりますので
# unless @user == current_user
# もし@userとcurrent_user(ログインしているユーザー)が一致してなければ、という意味になります。
# 一致していなかった場合、ログインしているuserのshowページにリダイレクトする仕組みになっています
  before_action :authenticate_user!
  # ページ遷移設定
  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def create
    @user = User.new(user_params)
    @book.save
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>

    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class='container' >
      <h2>Bookers</h2>
    <button class="navbar-toggler" type="button" data-togle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li><%= link_to 'Home', user_path(current_user), class: 'nav-link text-light' %></li>
          <li><%= link_to 'Users', users_path, class: 'nav-link text-light' %></li>
          <li><%= link_to 'Books', books_path, class: 'nav-link text-light'%></li>
          <li><%= link_to 'logout', destroy_user_session_path, method: :delete, class: 'nav-link text-light' %></li>
        <% else %>
          <li><%= link_to 'Home', root_path, class: 'nav-link text-light' %></li>
          <li><%= link_to 'About', about_path, class: 'nav-link text-light' %></li>
          <li><%= link_to 'sign up', new_user_registration_path, class: 'nav-link text-light' %></li>
          <li><%= link_to 'login', new_user_session_path, class: 'nav-link text-light'%></li>
        <% end %>
      </ul>
      </div>
    </div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2-debug</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <% if user_signed_in? %>

      <%= form_with url: search_path, method: :get, local: true do |search| %>
        <%= search.select 'range' ,options_for_select([['--選択してください--'],['User', '1'], ['Book', '2']]) %>
        <%= search.select 'search', options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"]]) %>
        <%= search.text_field (:word) %>
        <%= search.submit "検索" %>
      <% end %>
    <% end %>
    <p id="notice"><%= notice %></p>
      <main class="container">
        <div class="row">
            <%= yield %>
        </div>
      </main>

    <%= render 'layouts/footer' %>
  </body>
</html>